import Login from "../Login";
import Dashboard from "../Dashboard";
import css from "../../styles/Home.module.css";
import { useState, useEffect } from "react";
import Head from "next/head";

export default function Home() {
  const [cachedUsername, setCachedUsername] = useState(null);
  const [username, setUsername] = useState("");

  const handleUsernameChange = (e) => {
    setUsername(e.target.value);
  };

  const handleLogin = (e) => {
    e.preventDefault();
    localStorage.setItem("username", username);
    window.dispatchEvent(new Event("username"));
    setUsername("");
  };

  const handleLogout = () => {
    localStorage.setItem("username", "");
    window.dispatchEvent(new Event("username"));
  };

  useEffect(() => {
    const gotUsername = localStorage.getItem("username");
    if (gotUsername) {
      setCachedUsername(gotUsername);
    }
  }, []);

  useEffect(() => {
    window.addEventListener("username", () => {
      setCachedUsername(localStorage.getItem("username"));
    });

    return () =>
      window.removeEventListener("username", () =>
        setCachedUsername(localStorage.getItem("username"))
      );
  }, []);

  return (
    <div className={css.container}>
      <Head>
        <title>Quiz App: Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={css.main}>
        {cachedUsername ? (
          <Dashboard
            cachedUsername={cachedUsername}
            handleLogout={handleLogout}
          />
        ) : (
          <Login
            username={username}
            handleUsernameChange={handleUsernameChange}
            handleLogin={handleLogin}
          />
        )}
      </main>
    </div>
  );
}
